spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: storagerelay://https/${BASE_URL}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

  datasource:
    url: jdbc:mysql://${MYSQL_RW_HOSTNAME}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
