spring:
  redis:
    host: localhost
    port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${BASE_URL}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

  datasource:
    url: jdbc:mysql://${MYSQL_RW_HOSTNAME}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate

passport:
  public-key: ${RSA_PUBLIC_KEY}
  private-key: ${RSA_PRIVATE_KEY}

resources:
  user:
    default-picture: https://avatars.githubusercontent.com/u/60027496?v=4
