spring:
  profiles: 
    include:
    - core
    active: production

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
          github:
            client-id: ${G4B_CLIENT_ID}
            client-secret: ${G4B_CLIENT_SECRET}
