name: github-actions/gradle/build
on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: dev
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      G4B_CLIENT_ID: ${{ secrets.G4B_CLIENT_ID }}
      G4B_CLIENT_SECRET: ${{ secrets.G4B_CLIENT_SECRET }}
      REDIS_CLUSTER_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      MYSQL_RO_HOSTNAME: localhost:3306
      MYSQL_RW_HOSTNAME: localhost:3306
      MYSQL_USERNAME: moomark
      MYSQL_PASSWORD: 1q2w3e4r
      MYSQL_DATABASE: moomark-auth
      JWT_SECRET: abcdefghijklnmopqrstuvwxyz123456
      BASE_URL: http://localhost:8080/

    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379/tcp
      mysql:
        image: mysql:8.0.20
        ports:
          - 3306:3306/tcp
        env:
          MYSQL_DATABASE: moomark-auth
          MYSQL_USER: moomark
          MYSQL_PASSWORD: 1q2w3e4r
          MYSQL_ROOT_PASSWORD: 1q2w3e4r
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Verify MySql connection
        env:
          PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done

      - uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: java-${{ hashFiles('.gradle') }}

      - name: Run build
        run: ./gradlew build -x checkstyleMain -x test -x checkstyleTest--stacktrace

      - name: Run test
        run: ./gradlew test -x checkstyleMain -x checkstyleTest --stacktrace

      - name: Update artifact
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: auth-result
          path: ${{ github.workspace }}/build/reports
