name: github-actions/gradle/checkstyle
on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - develop

jobs:
  lint:
    name: Checkstyle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: backend-auth-java-${{ hashFiles('backend/auth/.gradle') }}
          restore-keys: backend-auth-java

      - name: Run all check
        run: ./gradlew check -x compileJava -x compileTestJava --stacktrace

      - name: Update artifact
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: auth-result
          path: backend/auth/build/reports
